apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: demo
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: webssl
      port: 443
      targetPort: 443
  selector:
    app: nginx-demo